### ISSUE TITLE
HTML5 validation happens but the form is still submitted

### ISSUE THREAD

**Issue by HeishPi** [thelia-modules/ReCaptcha#3]
Hello,

I contacted you weeks ago to mention that the module wouldn't let the HTML5 validation do her job and you fixed it. But now there's another issue : 

When I try to submit a form with an invisble Captcha while all the required inputs are not filled, the form validation happens (and those inputs are higlighted to warn the user) but the Captcha still launches. And if you complete it, the form is submitted, despite that the validation failed. And it gives an error template.

That would be best for customer experience to prevent that. Is it possible to execute the Captcha only if the form validation returns True ?

Thanks for your attention !

**Comment by HeishPi** [comment]
Not sure if a PR is really necessary, so I give you what worked for me.

I edited the recaptcha-js.html file like this : 

`<script src="https://www.google.com/recaptcha/api.js?hl={lang attr="code"}" async defer></script>
<script>
    window.onload = function() {
        var captchaDiv = document.getElementById("recaptcha-invisible");
        console.log(captchaDiv);
        if (captchaDiv !== null) {
            var form = captchaDiv.parentElement;

            form.addEventListener("submit", function(event) {
                if (!grecaptcha.getResponse()) {
                    event.preventDefault(); //prevent form submit
                    grecaptcha.execute();
                }
            });

            onCompleted = function() {
                if(form.reportValidity() !== false) {
                    form.submit();
                }

            }
        }
    }
</script>`

It's not really beautiful, as the submit button won't work at all until you fulfill all the required inputs. But it's effective !

**Comment by lopes-vincent** [comment]
Hello, 
You are right this need to be fixed.

I tried your solution, it work well but I don't understand why do you say "the submit button won't work at all until you fulfill all the required inputs" ?

**Comment by HeishPi** [comment]
I was just saying that is not really user friendly, as it's not very clear that you have to fulfill all required inputs when repetitively trying to submit the form (but that is exactly why I'm here for, eheh. I'll had a little alert to explain why the submit button won't work, telling the user to fulfill the required inputs).

Are you gonna change your module with the solution I find ? If so, I'd like to make a PR (my first ever !).

**Comment by lopes-vincent** [comment]
It's ok for me you can make your PR 😉
Can you please update the version to 2.0.2 in module.xml in your PR ?
Thanks !
